const HEURISTICS = {
    TOTEM_POLE: {
        CATEGORY_WEIGHT: 4,
    },
};

const AGGREGATOR = {
    SAMPLE_INTERVAL: 180000,
};

const TRACKER = {
    HEARTBEAT_INTERVAL: 30000,
};

export const CONSTANTS = { HEURISTICS, AGGREGATOR, TRACKER };
